radarr:
  radarr_merged:
    base_url: http://localhost:7878
    api_key: !secret radarr_api_key

    media_naming:
      folder: default
      movie:
        rename: true
        standard: jellyfin

    quality_definition:
      type: movie

    quality_profiles:
      - name: HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080P
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: Bluray-720p

      - name: UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBRip-2160p
              - WEBDL-2160p


      - name: Remux + WEB 1080p
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Remux-1080p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Remux-1080p
          - name: WEB 1080p
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p

      - name: Remux + WEB 2160p
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Remux-2160p
          until_score: 10000
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Remux-2160p
          - name: WEB 2160p
            qualities:
              - WEBRip-2160p
              - WEBDL-2160p

    custom_formats:
      - trash_ids:
          # General section for multiple Quality Profiles
          # Release Groups
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03
          # Repacks
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3
          # Unwanted
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - e6886871085226c3da1830830146846c # Generated Dynamic HDR
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - 0a3f082873eb454bde444150b70253cc # Extras
          - 712d74cd88bceb883ee32f773656b1f5 # Sing-Along Versions
          - cae4ca30163749b891686f95532519bd # AV1
          # General Streaming Services
          - b3b3a6ac74ecbd56bcdbefa4799fb9df # AMZN
          - 40e9380490e748672c2522eaaeb692f7 # ATVP
          - cc5e51a9e85a6296ceefe097a77f12f4 # BCORE
          - 16622a6911d1ab5d5b8b713d5b0036d4 # CRiT
          - 84272245b2988854bfb76a16e60baea5 # DSNP
          - 509e5f41146e278f9eab1ddaceb34515 # HBO
          - 5763d1b0ce84aff3b21038eea8e9b8ad # HMAX
          - 526d445d4c16214309f0fd2b3be18a89 # Hulu
          - e0ec9672be6cac914ffad34a6b077209 # iT
          - 6a061313d22e51e0f25b7cd4dc065233 # MAX
          - 2a6039655313bf5dab1e43523b62c374 # MA
          - 170b1d363bd8516fbf3a3eb05d4faff6 # NF
          - e36a0ba1bc902b26ee40818a1d59b8bd # PMTP
          - c9fd353f8f5f1baf56dc601c4cb29920 # PCOK
          - c2863d2a50c9acad1fb50e53ece60817 # STAN
          # Misc
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - cc444569854e9de0b084ab2b8b1532b2 # Black and White Editions
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (No WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGRoup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
          # Movie Versions
          - 570bc9ebecd92723d2d21500f4be314c # Remaster
          - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          - 957d0f44b592285f26449575e8b1167e # Special Edition
          - eecf3a857724171f968a66cb5719e152 # IMAX
          - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
          - 0f12c086e289cf966fa5948eac571f44 # Hybrid
        assign_scores_to:
          - name: HD Bluray + WEB
          - name: UHD Bluray + WEB
          - name: Remux + WEB 1080p
          - name: Remux + WEB 2160p

      - trash_ids:
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
        assign_scores_to:
          - name: HD Bluray + WEB

      - trash_ids:
          # Release Grops
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux TIer 02
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
        assign_scores_to:
          - name: Remux + WEB 1080p

      - trash_ids:
          # General section for UHD quality profiles
          # Misc
          - e23edd2482476e595fb990b12e7c609c # DV HDR10
          - c53085ddbd027d9624b320627748612f # DV HDR10+
          - b974a6cd08c1066250f1f177d7aa1225 # HDR10+
          - dfb86d5941bc9075d6af23b09c2aeecd # HDR10
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL) - Unwanted
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
          - 9c38ebb7384dada637be8899efa68e6f # SDR - Unwanted
        assign_scores_to:
          - name: UHD Bluray + WEB
          - name: Remux + WEB 2160p

      - trash_ids:
          # Release Groups
          - 4d74ac4c4db0b64bff6ce0cffef99bf0 # UHD Bluray Tier 01
          - a58f517a70193f8e578056642178419d # UHD Bluray TIer 02
          - e71939fae578037e7aed3ee219bbe7c1 # UHD Bluray Tier 03
        assign_scores_to:
          - name: UHD Bluray + WEB

      - trash_ids:
          # Release Grops
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux TIer 02
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
        assign_scores_to:
          - name: Remux + WEB 2160p


sonarr:
  sonarr_merged:
    base_url: http://localhost:8989
    api_key: !secret sonnarr_api_key

    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    quality_definition:
      type: series

    quality_profiles:
      - name: HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-1080p
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-1080p
          - name: WEB 1080P
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: Bluray-720p
          - name: WEB 720P
            qualities:
              - WEBRip-720p
              - WEBDL-720p


      - name: HD WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEB 1080p
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: WEB 1080P
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: WEB 720P
            qualities:
              - WEBRip-720p
              - WEBDL-720p

      - name: UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: Bluray-2160p
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Bluray-2160p
          - name: WEB 2160p
            qualities:
              - WEBRip-2160p
              - WEBDL-2160p
          - name: Bluray-1080p
          - name: WEB 1080P
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: Bluray-720p
          - name: WEB 720P
            qualities:
              - WEBRip-720p
              - WEBDL-720p

      - name: UHD WEB
        reset_unmatched_scores:
          enabled: true
        upgrade:
          allowed: true
          until_quality: WEB 2160p
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: WEB 2160p
            qualities:
              - WEBRip-2160p
              - WEBDL-2160p
          - name: WEB 1080P
            qualities:
              - WEBRip-1080p
              - WEBDL-1080p
          - name: WEB 720P
            qualities:
              - WEBRip-720p
              - WEBDL-720p

    custom_formats:
      - trash_ids:
          # General section for multiple Quality Profiles
          # Release Groups
          - e6258996055b9fbab7e9cb2f75819294 # WEB Tier 01
          - 58790d4e2fdcd9733aa7ae68ba2bb503 # WEB Tier 02
          - d84935abd3f8556dcd51d4f27e22d0a6 # WEB Tier 03
          - d0c516558625b04b363fa6c5c2c7cfd4 # WEB Scene
          # Repacks
          - ec8fa7296b64e8cd390a1600981f3923 # Repack/Proper
          - eb3d5cc0a2be0db205fb823640db6a3c # Repack v2
          - 44e7c4de10ae50265753082e5dc76047 # Repack v3
          # Unwanted
          - 85c61753df5da1fb2aab6f2a47426b09 # BR-DISK
          - 9c11cd3f07101cdba90a2d81cf0e56b4 # LQ
          - e2315f990da2e2cbfc9fa5b7a6fcfe48 # LQ (Release title)
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          - fbcb31d8dabd2a319072b84fc0b7249c # Extras
          - 15a05bc7c1a36e2b57fd628f8977e2fc #AV1
          # General Streaming Services
          - d660701077794679fd59e8bdf4ce3a29 # AMZN
          - f67c9ca88f463a48346062e8ad07713f # AVTP
          - 77a7b25585c18af08f60b1547bb9b4fb # CC
          - 36b72f59f4ea20aad9316f475f2d9fbb # DCU
          - 89358767a60cc28783cdc3d0be9388a4 # DSNP
          - a880d6abc21e7c16884f3ae393f84179 # HMAX
          - 7a235133c87f7da4c8cccceca7e3c7a6 # HBO
          - f6cce30f1733d5c8194222a7507909bb # HULU
          - 0ac24a2a68a9700bcb7eeca8e5cd644c # iT
          - 81d1fbf600e2540cee87f3a23f9d3c1c # MAX
          - d34870697c9db575f17700212167be23 # NF
          - c67a75ae4a1715f2bb4d492755ba4195 # PMTP
          - 1656adc6d7bb2c8cca6acfb6592db421 # PCOK
          - ae58039e1319178e6be73caab5c42166 # SHO
          - 1efe8da11bfd74fbbcd4d8117ddb9213 # STAN
          - 9623c5c9cac8e939c1b9aedd32f640bf # SYFY
          # Misc
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
        - name: HD WEB
        - name: HD Bluray + WEB
        - name: UHD WEB
        - name: UHD Bluray + WEB

      - trash_ids:
          # General Sectton for UHD Quality Profiles
          - 2b239ed870daba8126a53bd5dc8dc1c8 # DV HDR10+
          - 7878c33f1963fefb3d6c8657d46c2f0a # DV HDR10
          - a3d82cbef5039f8d295478d28a887159 # HDR10+
          - 3497799d29a085e2ac2df9d468413c94 # HDR10
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL) - Unwanted
          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (NO HDR/DEV) - 1080p - Unwanted
          - 43b3cf48cb385cd3eac608ee6bca7f09 # UHD Streaming Boost
          - d2d299244a92b8a52d4921ce3897a256 # UHD Streaming Cut
        assign_scores_to:
          - name: UHD WEB
          - name: UHD Bluray + WEB
