# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-613256b0-7d22-46d8-b0c7-c48d129896f8";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-613256b0-7d22-46d8-b0c7-c48d129896f8".device = "/dev/disk/by-uuid/613256b0-7d22-46d8-b0c7-c48d129896f8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D531-FE05";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
