# Use Arch Linux as the base image
FROM archlinux:latest

# Update the package database and install necessary packages
RUN pacman -Syu --noconfirm \
    git \
    base-devel \
    sudo \
    clang \
    cmake \
    lld \
    av1an \
    ffmpeg \
    wget \
    nasm \
    --needed

# Create a temporary user for building yay and set up passwordless sudo
RUN useradd -m builduser && \
    echo 'builduser ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builduser && \
    chmod 0440 /etc/sudoers.d/builduser


# Create build directory
RUN mkdir /build && \
    chmod 777 /build

# Switch to the build user
USER builduser

# Clone & build AOCC
RUN cd /build && \
    git clone https://aur.archlinux.org/aocc.git aocc && \
    cd aocc && \
    wget https://download.amd.com/developer/eula/aocc/aocc-5-0/aocc-compiler-5.0.0.tar && \
    makepkg -si --noconfirm

# Set up AOCC environment and build svt-av1-psy
RUN bash -c " cd /build && \
    source /opt/aocc/setenv_AOCC.sh && \
    export CC=clang && \
    export CXX=clang++ && \
    export LD=lld && \
    cd /build && \
    git clone https://github.com/psy-ex/svt-av1-psy --depth 25 && \
    cd svt-av1-psy && \
    mkdir svt_build && cd svt_build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DSVT_AV1_LTO=OFF -DNATIVE=ON -DCMAKE_CXX_FLAGS=\"-flto=full\" -DCMAKE_C_FLAGS=\"-flto=full\" -DCMAKE_LD_FLAGS=\"-flto=full\" && \
    make -j$(nproc) && \
    sudo make install"

USER root

# Clean up (optional to reduce image size)
RUN rm -rf /build && \
    userdel builduser && \
    rm -rf /etc/sudoers.d/builduser

# Set the default command for the container
#CMD ["tail", "-f", "/dev/null"]
